version: 2.1

parameters:
  remote-trigger:
    type: boolean
    default: false
  project:
    type: string
    default: ""
  release-tag:
    type: string
    default: ""
  build-dir:
    type: string
    default: ""

jobs:
  trigger-submodule-update:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trigger
          command: scripts/trigger-submodule-update.sh

  update-generated-docs:
    docker:
      - image: cimg/go:1.14
    resource_class: small
    steps:
      - checkout
      - run:
          name: Setup git
          command: |
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "CircleCI"
            git config --global --unset url.ssh://git@github.com.insteadOf
            git config --global url."https://${GITHUB_TOKEN}:@github.com/".insteadOf "git@github.com:"
      - run:
          name: Update docs
          command: |
            scripts/update-generated-docs.sh \
              "<<pipeline.parameters.project>>" \
              "<<pipeline.parameters.release-tag>>" \
              "<<pipeline.parameters.build-dir>>"

workflows:
  docgen:
    when: << pipeline.parameters.project >>
    jobs:
      - trigger-submodule-update:
          filters:
            branches:
              only: master
